apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    name: main-port
  - port: 9000
    targetPort: 9000
    name: healh-port
  selector:
    app: keycloak