apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  ports:
  - name: standard-mongo-port
    port: 27017
    targetPort: 27017
  - name: reserve-mongo-port
    port: 27018
    targetPort: 27017
  selector:
    app: mongo-db
