apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-twin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-twin
  template:
    metadata:
      labels:
        app: digital-twin
    spec:
      containers:
      - name: digital-twin
        image: ghcr.io/smart-droplets-project/digitaltwinframework/digitaltwin:a1fb3475164cb339b459ceded1f2f0e746e46ad3
        ports:
        - containerPort: 8000
