apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-vm-max-map-count
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: sysctl-vm-max-map-count
  template:
    metadata:
      labels:
        name: sysctl-vm-max-map-count
    spec:
      hostPID: true
      containers:
      - name: sysctl
        image: busybox:1.34
        command:
        - sh
        - -c
        - |
          sysctl -w vm.max_map_count=262144
          sleep infinity
        securityContext:
          privileged: true
      restartPolicy: Always
