apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --provider=keycloak-oidc
            - --oidc-issuer-url=http://keycloak:8080/realms/smart-droplets-realm
            - --client-id=oauth2-proxy
            - --client-secret=eW91ci1jbGllbnQtc2VjcmV0
            - --cookie-secret=iLdaDMOyQM1ETZCktgJUa6pWszD78ynzIj5l9TWWkCY=
            - --email-domain=*
            - --skip-provider-button=true
            - --pass-authorization-header=true
            - --pass-access-token=true
            - --set-authorization-header=true
            - --skip-auth-strip-headers=true
            - --http-address=0.0.0.0:4180
            - --skip-auth-preflight=true
            - --skip-jwt-bearer-tokens=true
            - --upstream=http://orion:1026/ngsi-ld/v1/
            - --upstream=http://quantumleap:8668/v2/
          ports:
            - containerPort: 4180